'use server';

/**
 * @fileOverview This file defines a Genkit flow for AI-assisted grading of essays based on a rubric.
 *
 * - assistTeacherGrading - A function that grades an essay based on a rubric and generates preliminary scores.
 * - AssistTeacherGradingInput - The input type for the assistTeacherGrading function.
 * - AssistTeacherGradingOutput - The return type for the assistTeacherGrading function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AssistTeacherGradingInputSchema = z.object({
  essayText: z.string().describe('The text of the essay to be graded.'),
  rubricText: z.string().describe('The rubric to use for grading the essay.'),
});
export type AssistTeacherGradingInput = z.infer<typeof AssistTeacherGradingInputSchema>;

const AssistTeacherGradingOutputSchema = z.object({
  preliminaryScore: z.number().describe('The preliminary score generated by the AI, out of 100.'),
  feedback: z.string().describe('Detailed feedback on how the essay meets the rubric requirements.'),
});
export type AssistTeacherGradingOutput = z.infer<typeof AssistTeacherGradingOutputSchema>;

export async function assistTeacherGrading(input: AssistTeacherGradingInput): Promise<AssistTeacherGradingOutput> {
  return assistTeacherGradingFlow(input);
}

const prompt = ai.definePrompt({
  name: 'assistTeacherGradingPrompt',
  input: {schema: AssistTeacherGradingInputSchema},
  output: {schema: AssistTeacherGradingOutputSchema},
  prompt: `You are an AI assistant for teachers. Your task is to grade an essay based on a provided rubric.

Carefully analyze the essay and the rubric. Provide a preliminary score out of 100 and generate constructive feedback that explains how the score was determined based on each criterion in the rubric.

You MUST output your response in a valid JSON format.

Essay Text:
{{essayText}}

Rubric:
{{rubricText}}
`,
});

const assistTeacherGradingFlow = ai.defineFlow(
  {
    name: 'assistTeacherGradingFlow',
    inputSchema: AssistTeacherGradingInputSchema,
    outputSchema: AssistTeacherGradingOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
